// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

import "@openzeppelin/contracts/token/ERC721/ERC721.sol";
import "@openzeppelin/contracts/token/ERC721/extensions/ERC721URIStorage.sol";
import "@openzeppelin/contracts/access/Ownable2Step.sol";
import "@openzeppelin/contracts/utils/Nonces.sol";
import "@openzeppelin/contracts/utils/cryptography/ECDSA.sol";
import "@openzeppelin/contracts/utils/cryptography/MessageHashUtils.sol";

/**
 * @title SurvivalNFT
 * @dev ERC721 NFT contract representing game characters, weapons, items, and procedural loot.
 * Implements standard minting as well as secure, gasless server-side signed minting (mintWithSignature).
 */
contract SurvivalNFT is ERC721URIStorage, Ownable2Step, Nonces {
    using ECDSA for bytes32;

    // Address authorized to sign mint requests (the game's backend authority)
    address public trustedSigner;
    
    // Global tracker for automatic sequential IDs (for fallback admin minting)
    uint256 private _nextTokenId = 1;
    
    // Maximum total supply to prevent unbounded minting
    uint256 public constant MAX_SUPPLY = type(uint256).max;
    
    // Maximum URI length to prevent DOS attacks
    uint256 public constant MAX_URI_LENGTH = 2048;

    event SignerUpdated(address indexed oldSigner, address indexed newSigner);
    event NFTMinted(address indexed to, uint256 indexed tokenId, string tokenURI);
    event SignatureMintAttempted(address indexed to, uint256 indexed tokenId, bool success, string reason);

    constructor(address _trustedSigner) 
        ERC721("Survivalist Celestial NFTs", "SCN") 
        Ownable(msg.sender) 
    {
        require(_trustedSigner != address(0), "Invalid signer address");
        trustedSigner = _trustedSigner;
        emit SignerUpdated(address(0), _trustedSigner);
    }

    /**
     * @dev Update the trusted backend signing address.
     * @param _newSigner The new authorized signer address
     */
    function setTrustedSigner(address _newSigner) external onlyOwner {
        require(_newSigner != address(0), "Invalid signer address");
        emit SignerUpdated(trustedSigner, _newSigner);
        trustedSigner = _newSigner;
    }

    /**
     * @dev Admin direct mint function.
     * @param to The recipient address
     * @param tokenURI The metadata URI pointing to JSON (IPFS/JSON files)
     * @return The newly minted token ID
     */
    function adminMint(address to, string calldata tokenURI) external onlyOwner returns (uint256) {
        require(_nextTokenId < MAX_SUPPLY, "Token ID overflow");
        require(bytes(tokenURI).length > 0 && bytes(tokenURI).length <= MAX_URI_LENGTH, "Invalid token URI");
        require(to != address(0), "Cannot mint to zero address");
        
        uint256 id = _nextTokenId;
        _nextTokenId++;
        _safeMint(to, id);
        _setTokenURI(id, tokenURI);
        emit NFTMinted(to, id, tokenURI);
        return id;
    }

    /**
     * @dev Mint with cryptographic backend signature.
     * Prevents clients from unauthorized minting while saving them from direct backend-paid gas fees.
     * @param to The recipient address (player's Web3 wallet)
     * @param tokenId The specific procedural Item ID (generated by the game or matching randomized loot)
     * @param tokenURI The metadata URI pointing to JSON (IPFS/JSON files)
     * @param signature The ECDSA signature proving authorization from trustedSigner
     */
    function mintWithSignature(
        address to,
        uint256 tokenId,
        string calldata tokenURI,
        bytes calldata signature
    ) external {
        require(to != address(0), "Cannot mint to zero address");
        require(bytes(tokenURI).length > 0 && bytes(tokenURI).length <= MAX_URI_LENGTH, "Invalid token URI");
        require(_ownerOf(tokenId) == address(0), "Token ID already exists");

        // Use nonce to prevent replay attacks
        uint256 nonce = _useNonce(to);

        // Recreate the message hash signed by the backend
        bytes32 messageHash = keccak256(
            abi.encodePacked(to, tokenId, tokenURI, nonce, address(this))
        );
        
        // Convert to Ethereum signed message hash
        bytes32 ethSignedMessageHash = MessageHashUtils.toEthSignedMessageHash(messageHash);

        // Recover signer and verify it matches our trustedSigner
        address recoveredSigner = ethSignedMessageHash.recover(signature);
        
        if (recoveredSigner != trustedSigner) {
            emit SignatureMintAttempted(to, tokenId, false, "Invalid signature");
            revert("Invalid transaction signature");
        }

        // Perform safe mint
        _safeMint(to, tokenId);
        _setTokenURI(tokenId, tokenURI);

        emit NFTMinted(to, tokenId, tokenURI);
        emit SignatureMintAttempted(to, tokenId, true, "Success");
    }
}
