// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

import "@openzeppelin/contracts/token/ERC721/ERC721.sol";
import "@openzeppelin/contracts/token/ERC721/extensions/ERC721URIStorage.sol";
import "@openzeppelin/contracts/access/Ownable.sol";
import "@openzeppelin/contracts/utils/cryptography/ECDSA.sol";
import "@openzeppelin/contracts/utils/cryptography/MessageHashUtils.sol";

/**
 * @title SurvivalNFT
 * @dev ERC721 NFT contract representing game characters, weapons, items, and procedural loot.
 * Implements standard minting as well as secure, gasless server-side signed minting (mintWithSignature).
 */
contract SurvivalNFT is ERC721URIStorage, Ownable {
    using ECDSA for bytes32;

    // Address authorized to sign mint requests (the game's backend authority)
    address public trustedSigner;
    
    // Map of used nonces to prevent double-minting / replay attacks
    mapping(uint256 => bool) public usedNonces;
    
    // Global tracker for automatic sequential IDs (for fallback admin minting)
    uint256 private _nextTokenId = 1;

    event SignerUpdated(address indexed oldSigner, address indexed newSigner);
    event NFTMinted(address indexed to, uint256 indexed tokenId, string tokenURI);

    constructor(address _trustedSigner) 
        ERC721("Survivalist Celestial NFTs", "SCN") 
        Ownable(msg.sender) 
    {
        trustedSigner = _trustedSigner;
        emit SignerUpdated(address(0), _trustedSigner);
    }

    /**
     * @dev Update the trusted backend signing address.
     */
    function setTrustedSigner(address _newSigner) external onlyOwner {
        require(_newSigner != address(0), "Invalid signer address");
        emit SignerUpdated(trustedSigner, _newSigner);
        trustedSigner = _newSigner;
    }

    /**
     * @dev Admin direct mint function.
     */
    function adminMint(address to, string calldata tokenURI) external onlyOwner returns (uint256) {
        uint256 id = _nextTokenId;
        _nextTokenId++;
        _safeMint(to, id);
        _setTokenURI(id, tokenURI);
        emit NFTMinted(to, id, tokenURI);
        return id;
    }

    /**
     * @dev Mint with cryptographic backend signature.
     * Prevents clients from unauthorized minting while saving them from direct backend-paid gas fees.
     * @param to The recipient address (player's Web3 wallet)
     * @param tokenId The specific procedural Item ID (generated by the game or matching randomized loot)
     * @param tokenURI The metadata URI pointing to JSON (IPFS/JSON files)
     * @param nonce A unique nonce to prevent replay attacks
     * @param signature The ECDSA signature proving authorization from trustedSigner
     */
    function mintWithSignature(
        address to,
        uint256 tokenId,
        string calldata tokenURI,
        uint256 nonce,
        bytes calldata signature
    ) external {
        require(!usedNonces[nonce], "Nonce already used");
        require(!_exists(tokenId), "Token ID already exists"); // Ensure it isn't minted

        // Recreate the message hash signed by the backend
        bytes32 messageHash = keccak256(
            abi.encode(to, tokenId, keccak256(bytes(tokenURI)), nonce, address(this), block.chainid)
        );
        
        // Convert to Ethereum signed message hash
        bytes32 ethSignedMessageHash = MessageHashUtils.toEthSignedMessageHash(messageHash);

        // Recover signer and verify it matches our trustedSigner
        address recoveredSigner = ethSignedMessageHash.recover(signature);
        require(recoveredSigner == trustedSigner, "Invalid transaction signature");

        // Mark nonce as used
        usedNonces[nonce] = true;

        // Perform safe mint
        _safeMint(to, tokenId);
        _setTokenURI(tokenId, tokenURI);

        emit NFTMinted(to, tokenId, tokenURI);
    }

    /**
     * @dev Helper to check if a token exists.
     */
    function _exists(uint256 tokenId) internal view returns (bool) {
        try this.ownerOf(tokenId) returns (address) {
            return true;
        } catch {
            return false;
        }
    }
}
